### ISSUE TITLE
obscure error while using openstack as provider in `sfn list`

### ISSUE THREAD

**Issue by wallnerryan** [miasma-rb/miasma-open-stack#2]
`/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-open-stack-0.1.4/lib/miasma/contrib/open_stack.rb:190:in `new'` seems to point to a auth error but this stack trace is unclear.

I have the following vars set in my env.

```
OPENSTACK_IDENTITY_URL=https://cloud2.corp.com:5000/v3/
OPENSTACK_PASSWORD=<excluded>
OPENSTACK_PROJECT=corp
OPENSTACK_DOMAIN=corp
OPENSTACK_TENANT_NAME=demo
OPENSTACK_REGION=RegionOne
OPENSTACK_USER_ID=3d1e491f6ab89e8d0818e2741c08119648cf25abd37294d61c1da51ecd063a7f
OPENSTACK_USERNAME=rwallner
OPENSTACK_TOKEN=6a8ce137d235409fbf53404cb743d3a4
```

```
sfn list --debug
I, [2017-04-11T16:24:21.632659 #9867]  INFO -- : Lock aquired for stack update. Requesting stacks from upstream. (#<Thread:0x007fc58f07f448>)
ERROR: NoMethodError: undefined method `to_smash' for #<HTTP::Response:0x007fc58e8ff920>
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-0.3.2/lib/miasma/error.rb:31:in `initialize'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-open-stack-0.1.4/lib/miasma/contrib/open_stack.rb:190:in `new'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-open-stack-0.1.4/lib/miasma/contrib/open_stack.rb:190:in `identify_and_load'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-open-stack-0.1.4/lib/miasma/contrib/open_stack.rb:41:in `api_token'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-open-stack-0.1.4/lib/miasma/contrib/open_stack.rb:63:in `load!'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-open-stack-0.1.4/lib/miasma/contrib/open_stack.rb:34:in `service_catalog'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-open-stack-0.1.4/lib/miasma/contrib/open_stack.rb:309:in `endpoint_for'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-open-stack-0.1.4/lib/miasma/contrib/open_stack.rb:233:in `endpoint'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-0.3.2/lib/miasma/types/api.rb:106:in `block in request'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-0.3.2/lib/miasma/types/api.rb:105:in `tap'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-0.3.2/lib/miasma/types/api.rb:105:in `request'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-open-stack-0.1.4/lib/miasma/contrib/open_stack/orchestration.rb:155:in `stack_all'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-0.3.2/lib/miasma/models/orchestration/stacks.rb:28:in `perform_population'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-0.3.2/lib/miasma/types/collection.rb:22:in `block in all'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/bogo-0.2.8/lib/bogo/memoization.rb:64:in `memoize'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/miasma-0.3.2/lib/miasma/types/collection.rb:21:in `all'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/provider.rb:179:in `block in fetch_stacks'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/cache.rb:265:in `block in locked_action'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/cache.rb:321:in `lock'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/cache.rb:264:in `locked_action'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/provider.rb:172:in `fetch_stacks'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/provider.rb:102:in `cached_stacks'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/provider.rb:92:in `stacks'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/command/list.rb:38:in `get_stacks'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:35:in `method_missing'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/command/list.rb:14:in `block (3 levels) in execute!'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/command_module/callbacks.rb:19:in `api_action!'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:35:in `method_missing'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/command/list.rb:14:in `block (2 levels) in execute!'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:56:in `table'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/command/list.rb:13:in `block in execute!'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:78:in `instance_exec'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/bogo-ui-0.1.24/lib/bogo-ui/table.rb:78:in `display'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/lib/sfn/command/list.rb:31:in `execute!'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/bin/sfn:52:in `block (4 levels) in <top (required)>'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:26:in `block in bogo_cli_run'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/slop-3.6.0/lib/slop.rb:65:in `parse!'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/slop-3.6.0/lib/slop.rb:54:in `parse'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/bogo-cli-0.2.12/lib/bogo-cli/setup.rb:48:in `define'
/Users/rwallner/work/infrastructure/vendor/bundle/ruby/2.3.0/gems/sfn-3.0.22/bin/sfn:14:in `<top (required)>'
/Users/rwallner/.rvm/gems/ruby-2.3.3/bin/sfn:22:in `load'
/Users/rwallner/.rvm/gems/ruby-2.3.3/bin/sfn:22:in `<main>'
/Users/rwallner/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/Users/rwallner/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by wallnerryan** [comment]
Found that 

I assumed the identity URL to be `https://cloud2.corp.com:5000/v3/` but the following code makes it invalid.

e.join(credentials[:open_stack_identity_url], 'tokens')

the correct URL is `auth/tokens` and changing it to `https://cloud2.corp.com:5000/v3/auth/` produces the below with some `puts` on results of the HTTP request

```
{"error": {"message": "Expecting to find project, domain, OS-TRUST:trust or unscoped in scope - the server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error.", "code": 400, "title": "Bad Request"}}
{"error": {"message": "Expecting to find project, domain, OS-TRUST:trust or unscoped in scope - the server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error.", "code": 400, "title": "Bad Request"}}
ERROR: NoMethodError: undefined method `to_smash' for #<HTTP::Respo
```

**Comment by wallnerryan** [comment]
This PR https://github.com/miasma-rb/miasma-open-stack/pull/3 was able to fix `sfn list` i havent tried other commands yet.
